# Numpy -  multidimensional data arrays

Heavily based on the following sources:
* J.R. Johansson, [Scientific Computing with Python](http://jrjohansson.github.io).
* Jake VanderPlas,[Python Data Science Handbook](https://github.com/jakevdp/PythonDataScienceHandbook) 

In [87]:
# what is this line all about?!? Answer in matplotlib introduction
%matplotlib inline
import matplotlib.pyplot as plt
plt?

## Introduction

* The `numpy` package (module) is used in almost all numerical computation using Python. 
* It is implemented in C and Fortran so when calculations are vectorized (formulated with vectors and matrices), performance is very good. 

To use `numpy` you need to import the module, usually as following:

In [88]:
import numpy as np
np?

In the `numpy` package the terminology used for vectors, matrices and higher-dimensional data sets is *array*. 



## Creating `numpy` arrays

There are a number of ways to initialize new numpy arrays, for example from

* a Python list or tuples
* using functions that are dedicated to generating numpy arrays, such as `arange`, `linspace`, etc.
* reading data from files

In [89]:
# a matrix: the argument to the array function is a nested Python list
m = np.array([[1, 2], [3, 4]])
m

array([[1, 2],
       [3, 4]])

In [90]:
# create a range

x = np.arange(0, 10, 1) # arguments: start, stop, step
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
# using linspace, both end points ARE included
y = np.linspace(0, 10, 11)
y

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [94]:
# uniform random numbers in [0,1]
np.random.rand(5,5)

array([[0.51481201, 0.47782746, 0.19054211, 0.00522882, 0.11484522],
       [0.4771235 , 0.36998244, 0.60985104, 0.45142488, 0.88304741],
       [0.56919618, 0.85130278, 0.08875588, 0.23554521, 0.87175283],
       [0.23970797, 0.94352872, 0.29119589, 0.92753683, 0.20392009],
       [0.40886755, 0.87302579, 0.79830777, 0.94929845, 0.10944584]])

All the `m`, `x` and `y` objects are of the type `ndarray` that the `numpy` module provides.

In [96]:
type(m), type(x), type(y)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

## NumPy Array Attributes

In [97]:
m.ndim

2

In [98]:
m.shape

(2, 2)

In [99]:
m.size

4

Equivalently, we could use the function `numpy.shape` and `numpy.size`

In [100]:
np.shape(m)

(2, 2)

In [101]:
np.size(m)

4

#### Why `numpy.ndarray` instead of `list`

* Python lists can contain any kind of object. They are dynamically typed. They do not support mathematical functions such as matrix and dot multiplications, etc. Implementing such functions for Python lists would not be very efficient because of the dynamic typing.
* Numpy arrays are **statically typed** and **homogeneous**. The type of the elements is determined when the array is created.
* Because of the static typing, fast implementation of mathematical functions such as multiplication and addition of `numpy` arrays can be implemented in a compiled language (C and Fortran is used).

Using the `dtype` (data type) attribute of an `ndarray`, we can see what type the data of an array has:

In [102]:
m.dtype

dtype('int32')

If we want, we can explicitly define the type of the array data when we create it, using the `dtype` keyword argument: 

In [103]:
c = np.array([[1, 2], [3, 4]], dtype=complex)

c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

Common data types that can be used with `dtype` are: `int`, `float`, `complex`, `bool`, `object`, etc.

We can also explicitly define the bit size of the data types, for example: `int64`, `int16`, `float128`, `complex128`.

## Manipulating arrays

###  Basic manipulating: Indexing

We can index elements in an array using square brackets and indices:

In [104]:
# x is a vector, and has only one dimension, taking one index
x[0]

0

In [108]:
# m is a matrix, or a 2 dimensional array, taking two indices 
m
m[0,1]

2

If we omit an index of a multidimensional array it returns the whole row (or, in general, a N-1 dimensional array) 

In [107]:
m[0]

array([1, 2])

We can assign new values to elements in an array using indexing:

In [109]:
m[1,:] = 0
m[:,1] = -1
m

array([[ 1, -1],
       [ 0, -1]])

### Basic manipulating: Index Slicing

Index slicing is the technical name for the syntax `m[lower:upper:step]` to extract part of an array.
Negative indices counts from the end of the array (positive index from the begining):

In [111]:
x[:2] # the last three elements


array([0, 1])

Index slicing works exactly the same way for multidimensional arrays:

In [112]:
a = np.array([[n+m*10 for n in range(5)] for m in range(5)])
a

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [115]:
# a block from the original array
a[2:4, 2:]

array([[22, 23, 24],
       [32, 33, 34]])

### Basic manipulating: Fancy Indexing -- using an array or list as an index

In [118]:
row_indices = [0, 2, 3]
a[:, [0, 2, 3]]

array([[ 0,  2,  3],
       [10, 12, 13],
       [20, 22, 23],
       [30, 32, 33],
       [40, 42, 43]])

In [119]:
col_indices = [1, 2, -1] # remember, index -1 means the last element
a[row_indices, col_indices]

array([ 1, 22, 34])

We can also use index masks: If the index mask is an Numpy array of data type `bool`, then an element is selected (True) or not (False) depending on the value of the index mask at the position of each element: 

This feature is very useful to conditionally select elements from an array, using for example comparison operators:

In [124]:
x = np.arange(0, 10, 0.5)
x.size

20

In [126]:
mask = (5 < x)
mask.size

20

In [127]:
x[mask]

array([5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

### Basic manipulating: Element-Wise array operations

#### array-scalar operations

We can use the usual arithmetic operators to multiply, add, subtract, and divide arrays with scalar numbers.

In [27]:
a = a[:3, :3]
a

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [128]:
a * 2

array([[ 0,  2,  4,  6,  8],
       [20, 22, 24, 26, 28],
       [40, 42, 44, 46, 48],
       [60, 62, 64, 66, 68],
       [80, 82, 84, 86, 88]])

In [129]:
a + 2

array([[ 2,  3,  4,  5,  6],
       [12, 13, 14, 15, 16],
       [22, 23, 24, 25, 26],
       [32, 33, 34, 35, 36],
       [42, 43, 44, 45, 46]])

#### array-array operations

When we add, subtract, multiply and divide arrays with each other, the default behaviour is **element-wise** operations:

In [130]:
a * a # element-wise multiplication

array([[   0,    1,    4,    9,   16],
       [ 100,  121,  144,  169,  196],
       [ 400,  441,  484,  529,  576],
       [ 900,  961, 1024, 1089, 1156],
       [1600, 1681, 1764, 1849, 1936]])

If we multiply arrays with compatible shapes, we get an element-wise multiplication of each row:

In [133]:
np.arange(5) + np.arange(5)

array([0, 2, 4, 6, 8])

The geometry of these examples is visualized in the following figure

![Broadcasting Visual](figures/02.05-broadcasting.png)

## Mathematical Functions

`Numpy` package provides many mathematical functions, such as trigonometric functions, rounding, sums, products, etc.:

In [134]:
np.sin(a)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736],
       [ 0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836],
       [-0.98803162, -0.40403765,  0.55142668,  0.99991186,  0.52908269],
       [ 0.74511316, -0.15862267, -0.91652155, -0.83177474,  0.01770193]])

In [137]:
np.nan * np.zeros((5, 5))

array([[nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan]])

In [138]:
np.exp(a)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06],
       [4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09,
        2.64891221e+10],
       [1.06864746e+13, 2.90488497e+13, 7.89629602e+13, 2.14643580e+14,
        5.83461743e+14],
       [2.35385267e+17, 6.39843494e+17, 1.73927494e+18, 4.72783947e+18,
        1.28516001e+19]])

## Common used sub-modules of NumPy: Linear Algebra (`numpy.linalg`)

`numpy.linalg` sub-routine provides core linear algebra functions for `numpy` array:

In [139]:
np.linalg.det(a)

0.0

In [140]:
np.linalg.cond(a)

1.6103775099089318e+18

In [141]:
np.linalg.eig(a)

(array([ 1.14371710e+02, -4.37171044e+00, -1.45209432e-15, -9.41013251e-16,
         1.04913943e-15]),
 array([[ 4.77984239e-02,  6.58846679e-01,  6.32455532e-01,
          4.93504817e-01,  1.70216011e-01],
        [ 2.14091866e-01,  3.43221556e-01, -6.32455532e-01,
         -2.19707179e-01, -1.59004223e-01],
        [ 3.80385308e-01,  2.75964329e-02, -3.16227766e-01,
         -4.58383709e-01, -4.93153156e-01],
        [ 5.46678750e-01, -2.88028690e-01, -4.55239628e-16,
         -3.98130311e-01,  7.82454936e-01],
        [ 7.12972192e-01, -6.03653814e-01,  3.16227766e-01,
          5.82716382e-01, -3.00513568e-01]]))

In [142]:
np.linalg.qr(a)

(array([[ 0.00000000e+00, -7.74596669e-01,  6.21506557e-01,
         -7.77175152e-02,  8.76902901e-02],
        [-1.82574186e-01, -5.16397779e-01, -6.14903326e-01,
          5.09984483e-01,  2.48615621e-01],
        [-3.65148372e-01, -2.58198890e-01, -2.44082806e-01,
         -2.91851498e-01, -8.09472845e-01],
        [-5.47722558e-01,  1.11022302e-16, -1.53150640e-01,
         -6.35380393e-01,  5.22337667e-01],
        [-7.30296743e-01,  2.58198890e-01,  3.90630214e-01,
          4.94964923e-01, -4.91707326e-02]]),
 array([[-5.47722558e+01, -5.65979976e+01, -5.84237395e+01,
         -6.02494813e+01, -6.20752232e+01],
        [ 0.00000000e+00, -1.29099445e+00, -2.58198890e+00,
         -3.87298335e+00, -5.16397779e+00],
        [ 0.00000000e+00,  0.00000000e+00,  7.10976284e-15,
          1.39908985e-14,  1.09871061e-14],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          3.80969083e-16, -4.01253082e-15],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
  

In [143]:
np.linalg.svd(a)

(array([[-0.03522722, -0.77379522,  0.49196722, -0.39504558, -0.04367199],
        [-0.20587009, -0.50756035, -0.41300688,  0.43361234,  0.58429929],
        [-0.37651297, -0.24132547, -0.10155151,  0.46361409, -0.7581222 ],
        [-0.54715585,  0.0249094 , -0.52574523, -0.64788288, -0.06196549],
        [-0.71779873,  0.29114428,  0.5483364 ,  0.14570203,  0.27946039]]),
 array([1.30902293e+02, 3.81964279e+00, 6.43744025e-15, 1.77618438e-15,
        8.12867121e-17]),
 array([[-0.41798798, -0.43236943, -0.44675088, -0.46113233, -0.47551378],
        [ 0.65213959,  0.33623902,  0.02033844, -0.29556213, -0.61146271],
        [ 0.0062978 , -0.36600952,  0.16862683,  0.73558371, -0.54449882],
        [-0.63219984,  0.61761868,  0.33961809, -0.00329289, -0.32174405],
        [ 0.0168435 , -0.42963263,  0.81007687, -0.39862985,  0.00134211]]))

### Common used sub-modules of NumPy: Matrix Library (`numpy.matlib`)

For matrix mutiplication? There are two ways:
* We can either use the `numpy.dot` function, which applies a matrix-matrix, matrix-vector, or inner vector multiplication to its two arguments: 

In [144]:
np.dot(a, a)

array([[ 300,  310,  320,  330,  340],
       [1300, 1360, 1420, 1480, 1540],
       [2300, 2410, 2520, 2630, 2740],
       [3300, 3460, 3620, 3780, 3940],
       [4300, 4510, 4720, 4930, 5140]])

In [148]:
a * a

array([[   0,    1,    4,    9,   16],
       [ 100,  121,  144,  169,  196],
       [ 400,  441,  484,  529,  576],
       [ 900,  961, 1024, 1089, 1156],
       [1600, 1681, 1764, 1849, 1936]])

In [149]:
v = np.arange(5)
np.dot(a, v)

array([ 30, 130, 230, 330, 430])

In [157]:
np.dot(v, v)

30

* Alternatively, we can cast the array objects to the type `numpy.matrix`. This changes the behavior of the standard arithmetic operators `+, -, *` to use matrix algebra.

In [151]:
mat = np.matrix(a)
vec = np.matrix(v).T # make it a column vector

In [161]:
mat.dot(mat)

matrix([[ 300,  310,  320,  330,  340],
        [1300, 1360, 1420, 1480, 1540],
        [2300, 2410, 2520, 2630, 2740],
        [3300, 3460, 3620, 3780, 3940],
        [4300, 4510, 4720, 4930, 5140]])

In [162]:
np.multiply(mat, mat)

matrix([[   0,    1,    4,    9,   16],
        [ 100,  121,  144,  169,  196],
        [ 400,  441,  484,  529,  576],
        [ 900,  961, 1024, 1089, 1156],
        [1600, 1681, 1764, 1849, 1936]])

In [154]:
mat * vec

matrix([[ 30],
        [130],
        [230],
        [330],
        [430]])

In [155]:
# inner product
vec.T * vec

matrix([[30]])

In [156]:
mat_array = np.array(mat)
mat_array

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [48]:
# with matrix objects, standard matrix algebra applies
vec + mat * vec

matrix([[ 5],
        [36],
        [67]])

If we try to add, subtract or multiply objects with incomplatible shapes we get an error:

In [49]:
mat2 = np.matrix([1,2,3,4,5,6]).T

In [50]:
mat2.shape, vec.shape

((6, 1), (3, 1))

In [51]:
mat2 * vec

ValueError: shapes (6,1) and (3,1) not aligned: 1 (dim 1) != 3 (dim 0)

See also the related functions: `inner`, `outer`, `cross`, `kron`, `tensordot`. Try for example `help(kron)`.

## Reshaping arrays

The shape of an Numpy array can be modified with `numpy.reshape`.

In [163]:
a

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [164]:
n, m = a.shape

In [167]:
b = a.reshape((1, n*m))
b

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30,
        31, 32, 33, 34, 40, 41, 42, 43, 44]])

In [55]:
b[0,0:5] = 5 # modify the array
b

array([[ 5,  5,  5,  5,  5, 12, 20, 21, 22]])

We can also use the function `flatten` to make a higher-dimensional array into a vector. 

In [168]:
b = a.flatten()
b

array([ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30, 31,
       32, 33, 34, 40, 41, 42, 43, 44])

In [57]:
b[0:5] = 10
b

array([10, 10, 10, 10, 10, 12, 20, 21, 22])

### concatenate

In [169]:
b = np.array([[5, 6, 7, 9, 8]])

In [170]:
np.concatenate((a, b), axis=0)

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44],
       [ 5,  6,  7,  9,  8]])

In [171]:
np.concatenate((a, b.T), axis=1)

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14,  6],
       [20, 21, 22, 23, 24,  7],
       [30, 31, 32, 33, 34,  9],
       [40, 41, 42, 43, 44,  8]])

## Copy and "deep copy"

To achieve high performance, assignments in Python usually do not copy the underlaying objects. This is important for example when objects are passed between functions, to avoid an excessive amount of memory copying when it is not necessary (technical term: pass by reference). 

In [172]:
A = np.array([[1, 2], [3, 4]])

A

array([[1, 2],
       [3, 4]])

In [173]:
# now B is referring to the same array data as A 
B = A 

In [174]:
# changing B affects A
B[0,0] = 10
B

array([[10,  2],
       [ 3,  4]])

In [180]:
A[1, 1] = 10
B

array([[-5,  2],
       [ 3,  4]])

If we want to avoid this behavior, so that when we get a new completely independent object `B` copied from `A`, then we need to do a so-called "deep copy" using the function `copy`:

In [176]:
B = np.copy(A)

In [177]:
# now, if we modify B, A is not affected
B[0,0] = -5

B

array([[-5,  2],
       [ 3,  4]])

In [178]:
A

array([[10,  2],
       [ 3,  4]])

## Iterating over array elements

Generally, we want to avoid iterating over the elements of arrays whenever we can (at all costs). The reason is that in a interpreted language like Python (or MATLAB), iterations are really slow compared to vectorized operations. 

However, sometimes iterations are unavoidable. For such cases, the Python `for` loop is the most convenient way to iterate over an array:

In [68]:
v = np.array([1,2,3,4])

for element in v:
    print(element)

1
2
3
4


In [69]:
M = np.array([[1,2], [3,4]])

for row in M:
    print("row", row)
    
    for element in row:
        print(element)

row [1 2]
1
2
row [3 4]
3
4


When we need to iterate over each element of an array and modify its elements, it is convenient to use the `enumerate` function to obtain both the element and its index in the `for` loop: 

In [70]:
for row_idx, row in enumerate(M):
    print("row_idx", row_idx, "row", row)
    
    for col_idx, element in enumerate(row):
        print("col_idx", col_idx, "element", element)
       
        # update the matrix M: square each element
        M[row_idx, col_idx] = element ** 2

row_idx 0 row [1 2]
col_idx 0 element 1
col_idx 1 element 2
row_idx 1 row [3 4]
col_idx 0 element 3
col_idx 1 element 4


In [71]:
# each element in M is now squared
M

array([[ 1,  4],
       [ 9, 16]])

## Vectorizing functions

As mentioned several times by now, to get good performance we should try to avoid looping over elements in our vectors and matrices, and instead use vectorized algorithms. The first step in converting a scalar algorithm to a vectorized algorithm is to make sure that the functions we write work with vector inputs.

In [72]:
def Theta(x):
    """
    Scalar implemenation of the Heaviside step function.
    """
    if x >= 0:
        return 1
    else:
        return 0

In [73]:
Theta(array([-3,-2,-1,0,1,2,3]))

NameError: name 'array' is not defined

OK, that didn't work because we didn't write the `Theta` function so that it can handle a vector input... 

To get a vectorized version of Theta we can use the Numpy function `vectorize`. In many cases it can automatically vectorize a function:

In [74]:
Theta_vec = np.vectorize(Theta)

In [75]:
Theta_vec(np.array([-3,-2,-1,0,1,2,3]))

array([0, 0, 0, 1, 1, 1, 1])

## Using arrays in conditions

When using arrays in conditions,for example `if` statements and other boolean expressions, one needs to use `any` or `all`, which requires that any or all elements in the array evalutes to `True`:

In [181]:
M

array([[ 1,  4],
       [ 9, 16]])

In [182]:
if (M > 5).any():
    print("at least one element in M is larger than 5")
else:
    print("no element in M is larger than 5")

at least one element in M is larger than 5


In [183]:
if (M > 5).all():
    print("all elements in M are larger than 5")
else:
    print("all elements in M are not larger than 5")

all elements in M are not larger than 5


## Type casting

Since Numpy arrays are *statically typed*, the type of an array does not change once created. But we can explicitly cast an array of some type to another using the `astype` functions (see also the similar `asarray` function). This always create a new array of new type:

In [79]:
M.dtype

dtype('int32')

In [80]:
M2 = M.astype(float)

M2

array([[ 1.,  4.],
       [ 9., 16.]])

In [81]:
M2.dtype

dtype('float64')

In [186]:
M3 = M.astype(bool)

mask = M3 == 1
mask

array([[ True,  True],
       [ True,  True]])

## File I/O

### Numpy's native file format

Useful when storing and reading back numpy array data. Use the functions `numpy.save`/`numpy.savez`/`numpy.savetxt` and `numpy.load`/`numpy.loads`/`numpy.loadtxt`:

In [190]:
print(m)
print(x)
file_name = "numpy_ndaary.txt"
np.savetxt(file_name, x)

!dir $file_name

5
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]
 Volume in drive C is Windows7_OS
 Volume Serial Number is 0A43-8415

 Directory of C:\localData\selfLearning\python\SIOTraning\ipynb

07/27/2018  10:43 AM               520 numpy_ndaary.txt
               1 File(s)            520 bytes
               0 Dir(s)  341,642,899,456 bytes free


In [84]:
load_m = np.load(file_name)
load_m.files

['matrix', 'x']

In [85]:
mat = load_m['matrix']
mat


array(3)

## Further reading

* http://numpy.scipy.org
* https://docs.scipy.org/doc/numpy-1.14.0/reference/index.html
* http://scipy.org/NumPy_for_Matlab_Users - A Numpy guide for MATLAB users.